name: ev_transform
version: '1.0.0'

profile: ev_transform

model-paths: ["models"]
macro-paths: ["macros"]

models:
  ev_transform:
    bronze:
      +materialized: incremental
      +schema: bronze
    silver:
      +materialized: incremental
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
