version: 2

sources:
  - name: landing
    schema: landing
    tables:
      - name: ev_raw_data
        loaded_at_field: el_loaded_timestamp
        freshness:
          error_after:
            count: 30
            period: day
